package com.ls_raheja.application_form.entity;

public enum States {

    Andhra_Pradesh,
    Arunachal_Pradesh,
    Assam,
    Bihar,
    Chhattisgarh,
    Goa,
    Gujarat,
    Haryana,
    Himachal_Pradesh,
    Jammu_And_Kashmir,
    Jharkhand,
    Karnataka,
    Kerala,
    Madhya_Pradesh,
    Maharashtra,
    Manipur,
    Meghalaya,
    Mizoram,
    Nagaland,
    Odisha,
    Punjab,
    Rajasthan,
    Sikkim,
    Tamil_Nadu,
    Telangana,
    Tripura,
    Uttarakhand,
    Uttar_Pradesh,
    West_Bengal,
    Andaman_And_Nicobar_Islands,
    Chandigarh,
    Dadra_And_Nagar_Haveli,
    Daman_And_Diu,
    Delhi,
    Lakshadweep,
    Puducherry,

}
